//
// Created by tunm on 2024/1/31.
//

#ifndef HYPERFACEREPO_INFORMATION_H
#define HYPERFACEREPO_INFORMATION_H

#define INSPIRE_FACE_VERSION_MAJOR_STR "1"
#define INSPIRE_FACE_VERSION_MINOR_STR "1"
#define INSPIRE_FACE_VERSION_PATCH_STR "6"

#endif //HYPERFACEREPO_INFORMATION_H
