# Use manylinux2014_x86 as the base image
FROM quay.io/pypa/manylinux2014_x86_64
# FROM skybro/ubuntu-cn:18

ARG https_proxy
ARG http_proxy
ARG all_proxy

# Set the working directory
WORKDIR /workspace

# Default to running Bash
CMD ["/bin/bash"]
